version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: publishable-tracker-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - publishable-tracker-network

volumes:
  mongodb_data:
    name: publishable-tracker-mongodb-data

networks:
  publishable-tracker-network:
    name: publishable-tracker-network 